name: Deploy Vue to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - 'astar-vue-vite/**'
      - '.github/workflows/astar-dev-web.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install & Build
        working-directory: ./astar-vue-vite
        run: |
          npm install
          npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: astar-dev
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./astar-vue-vite/dist
